{
 "title": "Basic",
 "description": "Basic reports",
 "tags": [
  "php",
  "performance"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "schema",
    "query": "SELECT DISTINCT Value FROM proton.dictionary WHERE Column = 'Schema'"
   },
   {
    "name": "server_name",
    "label": "server name",
    "query": "SELECT DISTINCT Value FROM proton.dictionary WHERE Column = 'ServerName'"
   },
   {
    "name": "hostname",
    "query": "SELECT DISTINCT Value FROM proton.dictionary WHERE Column = 'Hostname'"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "proton",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    sum(RequestCount) / 60 AS RequestPerSecond\nFROM $table\nWHERE $timeFilter\n   AND CASE WHEN $schema <> 'all' THEN Schema = $schema ELSE 1 END \n      AND CASE WHEN $hostname <> 'all' THEN HostnameID = cityHash64($hostname) ELSE 1 END \n      AND CASE WHEN $server_name <> 'all' THEN ServerNameID = cityHash64($server_name) ELSE 1 END\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(Timestamp), 30) * 30) * 1000 as t,     sum(RequestCount) / 60 AS RequestPerSecond FROM proton.base_report WHERE Timestamp >= toDateTime(1547448279)    AND CASE WHEN 'all' <> 'all' THEN Schema = 'all' ELSE 1 END        AND CASE WHEN 'all' <> 'all' THEN HostnameID = cityHash64('all') ELSE 1 END        AND CASE WHEN 'all' <> 'all' THEN ServerNameID = cityHash64('all') ELSE 1 END GROUP BY t ORDER BY t",
     "round": "0s",
     "table": "base_report"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "database": "proton",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \n    t, \n    RequestTimeMax, \n    RequestTimeQuantiles[1] AS RequestTime_P90,\n    RequestTimeQuantiles[2] AS RequestTime_P95,\n    RequestTimeQuantiles[3] AS RequestTime_P99\nFROM (\n    SELECT\n        $timeSeries as t\n        , maxMerge(RequestTimeMax) AS RequestTimeMax\n        , quantilesMerge(0.9,0.95,0.99)(RequestTimeQuantiles) AS RequestTimeQuantiles\n    FROM $table\n    WHERE $timeFilter \n      AND CASE WHEN $schema <> 'all' THEN Schema = $schema ELSE 1 END \n      AND CASE WHEN $hostname <> 'all' THEN HostnameID = cityHash64($hostname) ELSE 1 END \n      AND CASE WHEN $server_name <> 'all' THEN ServerNameID = cityHash64($server_name) ELSE 1 END \n    GROUP BY t\n    ORDER BY t\n) ORDER BY t",
     "rawQuery": "SELECT      t,      RequestTimeMax,      RequestTimeQuantiles[1] AS RequestTime_P90,     RequestTimeQuantiles[2] AS RequestTime_P95,     RequestTimeQuantiles[3] AS RequestTime_P99 FROM (     SELECT         (intDiv(toUInt32(Timestamp), 30) * 30) * 1000 as t         , maxMerge(RequestTimeMax) AS RequestTimeMax         , quantilesMerge(0.9,0.95,0.99)(RequestTimeQuantiles) AS RequestTimeQuantiles     FROM proton.base_report     WHERE Timestamp >= toDateTime(1547448279)        AND CASE WHEN 'all' <> 'all' THEN Schema = 'all' ELSE 1 END        AND CASE WHEN 'all' <> 'all' THEN HostnameID = cityHash64('all') ELSE 1 END        AND CASE WHEN 'all' <> 'all' THEN ServerNameID = cityHash64('all') ELSE 1 END      GROUP BY t     ORDER BY t ) ORDER BY t",
     "round": "0s",
     "table": "base_report"
    }
   ]
  },
  {
   "title": "Requests per second where status > 400",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "proton",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    $timeSeries as t,\n    Status,\n    sum(RequestCount) / 60 AS RequestPerSecond\nFROM $table\nWHERE $timeFilter AND Status > 400\n   AND CASE WHEN $schema <> 'all' THEN Schema = $schema ELSE 1 END \n      AND CASE WHEN $hostname <> 'all' THEN HostnameID = cityHash64($hostname) ELSE 1 END \n      AND CASE WHEN $server_name <> 'all' THEN ServerNameID = cityHash64($server_name) ELSE 1 END\nGROUP BY t, Status\nORDER BY t",
     "rawQuery": "SELECT     (intDiv(toUInt32(Timestamp), 30) * 30) * 1000 as t,     Status,     sum(RequestCount) / 60 AS RequestPerSecond FROM proton.base_report WHERE Timestamp >= toDateTime(1547448279) AND Status > 400    AND CASE WHEN 'all' <> 'all' THEN Schema = 'all' ELSE 1 END        AND CASE WHEN 'all' <> 'all' THEN HostnameID = cityHash64('all') ELSE 1 END        AND CASE WHEN 'all' <> 'all' THEN ServerNameID = cityHash64('all') ELSE 1 END GROUP BY t, Status ORDER BY t",
     "round": "0s",
     "table": "base_report"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "database": "proton",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \n    t, \n    UtimeMax, \n    UtimeQuantiles[1] AS P90,\n    UtimeQuantiles[2] AS P95,\n    UtimeQuantiles[3] AS P99\nFROM (\n    SELECT\n        $timeSeries as t\n        , maxMerge(UtimeMax) AS UtimeMax\n        , quantilesMerge(0.9,0.95,0.99)(UtimeQuantiles) AS UtimeQuantiles\n    FROM $table\n    WHERE $timeFilter \n      AND CASE WHEN $schema <> 'all' THEN Schema = $schema ELSE 1 END \n      AND CASE WHEN $hostname <> 'all' THEN HostnameID = cityHash64($hostname) ELSE 1 END \n      AND CASE WHEN $server_name <> 'all' THEN ServerNameID = cityHash64($server_name) ELSE 1 END \n    GROUP BY t\n    ORDER BY t\n) ORDER BY t",
     "rawQuery": "SELECT      t,      UtimeMax,      UtimeQuantiles[1] AS P90,     UtimeQuantiles[2] AS P95,     UtimeQuantiles[3] AS P99 FROM (     SELECT         (intDiv(toUInt32(Timestamp), 30) * 30) * 1000 as t         , maxMerge(UtimeMax) AS UtimeMax         , quantilesMerge(0.9,0.95,0.99)(UtimeQuantiles) AS UtimeQuantiles     FROM proton.base_report     WHERE Timestamp >= toDateTime(1547448279)        AND CASE WHEN 'all' <> 'all' THEN Schema = 'all' ELSE 1 END        AND CASE WHEN 'all' <> 'all' THEN HostnameID = cityHash64('all') ELSE 1 END        AND CASE WHEN 'all' <> 'all' THEN ServerNameID = cityHash64('all') ELSE 1 END      GROUP BY t     ORDER BY t ) ORDER BY t",
     "round": "0s",
     "table": "base_report"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "database": "proton",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \n    t, \n    MemoryFootprintMax AS Max, \n    MemoryFootprintQuantiles[1] AS P90,\n    MemoryFootprintQuantiles[2] AS P95,\n    MemoryFootprintQuantiles[3] AS P99\nFROM (\n    SELECT\n        $timeSeries as t\n        , maxMerge(MemoryFootprintMax) AS MemoryFootprintMax\n        , quantilesMerge(0.9,0.95,0.99)(MemoryFootprintQuantiles) AS MemoryFootprintQuantiles\n    FROM $table\n    WHERE $timeFilter \n      AND CASE WHEN $schema <> 'all' THEN Schema = $schema ELSE 1 END \n      AND CASE WHEN $hostname <> 'all' THEN HostnameID = cityHash64($hostname) ELSE 1 END \n      AND CASE WHEN $server_name <> 'all' THEN ServerNameID = cityHash64($server_name) ELSE 1 END \n    GROUP BY t\n    ORDER BY t\n) ORDER BY t",
     "rawQuery": "SELECT      t,      MemoryFootprintMax AS Max,      MemoryFootprintQuantiles[1] AS P90,     MemoryFootprintQuantiles[2] AS P95,     MemoryFootprintQuantiles[3] AS P99 FROM (     SELECT         (intDiv(toUInt32(Timestamp), 30) * 30) * 1000 as t         , maxMerge(MemoryFootprintMax) AS MemoryFootprintMax         , quantilesMerge(0.9,0.95,0.99)(MemoryFootprintQuantiles) AS MemoryFootprintQuantiles     FROM proton.base_report     WHERE Timestamp >= toDateTime(1547448279)        AND CASE WHEN 'all' <> 'all' THEN Schema = 'all' ELSE 1 END        AND CASE WHEN 'all' <> 'all' THEN HostnameID = cityHash64('all') ELSE 1 END        AND CASE WHEN 'all' <> 'all' THEN ServerNameID = cityHash64('all') ELSE 1 END      GROUP BY t     ORDER BY t ) ORDER BY t",
     "round": "0s",
     "table": "base_report"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "database": "proton",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "\n    SELECT\n        $timeSeries as t\n        , sum(DocumentSizeTotal) AS DocumentSizeTotal\n    FROM $table\n    WHERE $timeFilter \n      AND CASE WHEN $schema <> 'all' THEN Schema = $schema ELSE 1 END \n      AND CASE WHEN $hostname <> 'all' THEN HostnameID = cityHash64($hostname) ELSE 1 END \n      AND CASE WHEN $server_name <> 'all' THEN ServerNameID = cityHash64($server_name) ELSE 1 END \n    GROUP BY t\n    ORDER BY t\n",
     "rawQuery": "SELECT         (intDiv(toUInt32(Timestamp), 30) * 30) * 1000 as t         , sum(DocumentSizeTotal) AS DocumentSizeTotal     FROM proton.base_report     WHERE Timestamp >= toDateTime(1547448279)        AND CASE WHEN 'all' <> 'all' THEN Schema = 'all' ELSE 1 END        AND CASE WHEN 'all' <> 'all' THEN HostnameID = cityHash64('all') ELSE 1 END        AND CASE WHEN 'all' <> 'all' THEN ServerNameID = cityHash64('all') ELSE 1 END      GROUP BY t     ORDER BY t",
     "round": "0s",
     "table": "base_report"
    }
   ]
  },
  {
   "title": "TOP 10 slow scripts",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "database": "proton",
     "dateTimeColDataType": "Timestamp",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    dictGetString('Proton', 'Value', ScriptNameID) AS ScriptName\n    , RequestCount\n    , RequestTimeAvg\n    , RequestTimeMax\n    , RequestTimeQuantiles[1] AS RequestTime_90\n    , RequestTimeQuantiles[2] AS RequestTime_95\n    , RequestTimeQuantiles[3] AS RequestTime_99\n    , UtimeTotal\n    , StimeTotal\n    , formatReadableSize(TrafficTotal) AS TrafficTotal\n    , formatReadableSize(MemoryFootprintTotal) AS MemoryFootprintTotal\nFROM (\n    SELECT\n        ScriptNameID\n        , SUM(RequestCount)                    AS RequestCount\n        , maxMerge(RequestTimeMax)             AS RequestTimeMax\n        , SUM(RequestTimeTotal) / RequestCount AS RequestTimeAvg\n        , quantilesMerge(0.9,0.95,0.99)(RequestTimeQuantiles) AS RequestTimeQuantiles\n        , SUM(UtimeTotal)           AS UtimeTotal\n        , SUM(StimeTotal)           AS StimeTotal\n        , SUM(DocumentSizeTotal)    AS TrafficTotal\n        , SUM(MemoryFootprintTotal) AS MemoryFootprintTotal\n    FROM $table\n    WHERE $timeFilter\n      AND CASE WHEN $schema <> 'all' THEN Schema = $schema ELSE 1 END \n      AND CASE WHEN $hostname <> 'all' THEN HostnameID = cityHash64($hostname) ELSE 1 END \n      AND CASE WHEN $server_name <> 'all' THEN ServerNameID = cityHash64($server_name) ELSE 1 END\n    GROUP BY ScriptNameID\n    ORDER BY RequestTimeQuantiles[3] DESC \n    LIMIT 10\n) ORDER BY RequestTime_99 DESC ",
     "rawQuery": "SELECT     dictGetString('Proton', 'Value', ScriptNameID) AS ScriptName     , RequestCount     , RequestTimeAvg     , RequestTimeMax     , RequestTimeQuantiles[1] AS RequestTime_90     , RequestTimeQuantiles[2] AS RequestTime_95     , RequestTimeQuantiles[3] AS RequestTime_99     , UtimeTotal     , StimeTotal     , formatReadableSize(TrafficTotal) AS TrafficTotal     , formatReadableSize(MemoryFootprintTotal) AS MemoryFootprintTotal FROM (     SELECT         ScriptNameID         , SUM(RequestCount)                    AS RequestCount         , maxMerge(RequestTimeMax)             AS RequestTimeMax         , SUM(RequestTimeTotal) / RequestCount AS RequestTimeAvg         , quantilesMerge(0.9,0.95,0.99)(RequestTimeQuantiles) AS RequestTimeQuantiles         , SUM(UtimeTotal)           AS UtimeTotal         , SUM(StimeTotal)           AS StimeTotal         , SUM(DocumentSizeTotal)    AS TrafficTotal         , SUM(MemoryFootprintTotal) AS MemoryFootprintTotal     FROM proton.base_report     WHERE Timestamp >= toDateTime(1547448279)       AND CASE WHEN 'all' <> 'all' THEN Schema = 'all' ELSE 1 END        AND CASE WHEN 'all' <> 'all' THEN HostnameID = cityHash64('all') ELSE 1 END        AND CASE WHEN 'all' <> 'all' THEN ServerNameID = cityHash64('all') ELSE 1 END     GROUP BY ScriptNameID     ORDER BY RequestTimeQuantiles[3] DESC      LIMIT 10 ) ORDER BY RequestTime_99 DESC",
     "round": "0s",
     "table": "base_report"
    }
   ]
  }
 ]
}